# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CasaDigital' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftMQTT'

  # Pods for CasaDigital

  target 'CasaDigitalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CasaDigitalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
